interface=wlan1
ssid=testnetwork

hw_mode=g
channel=1

auth_algs=1
eapol_version=2

# For both WPA2 and WPA3 we must specify wpa=2
wpa=2

#using internal server
eap_server=1
#certification
ca_cert=ca.pem
server_cert=server.pem
private_key=server.key


# Use wpa_key_mgmt=SAE for WPA3
wpa_key_mgmt=WPA-EAP
rsn_pairwise=CCMP
wpa_pairwise=TKIP

ieee8021x=1
eap_user_file=hostapd.eap_user
logger_syslog=-1
logger_syslog_level=4
logger_stdout=-1
logger_stdout_level=4

