# Configuration file containing all variable properties of the test harness.

# Change this to your dongle ID if you want to test a real device.
interface=wlan1

# Socket address of your learnlib host. These parameters should not change
learnlib_host=localhost
learnlib_port=8080

# Address of your client under test.
client_host=localhost
client_port=9090

# iwd, wpa_supplicant, or anonymous wpa_supplicant. Remove this line if you are testing a remote client
local_sut=wpa_supplicant

# You can test PEAP version 0 or 1. Changing this parameter will change the PEAP version parameter in the outer tunnel of the packet.
peap_version=0
