type = socket
hostname = 127.0.0.1
port = 8080
#alphabet = id_request_v0 challenge_v0 tlv_request tlv_failure success_request_all_zeros_v0 \
#  success_request_with_credentials_v0 success_and_cryptobinding cryptobinding eap_success 4_way_message_1

alphabet = id_request_v1 challenge_v1 success_request_all_zeros_v1 success_request_with_credentials_v1 \
  inner_success inner_failure eap_success 4_way_message_1
#lstar,dhc,kv,ttt,mp,rs
learning_algorithm=lstar

#wmethod,wpmethod,randomwords
eqtest=modifiedwmethod

# Remaining number of states that the equivalence checker assume exists when
# looking for a trace that contradicts the current hypothesis.
# Only needed for w-method
max_depth=2

# Time learning handling
time_learn=true
disable_outputs = deauthentication 4_way_message_2 disassociation no_reply tls_bad_cipher_exception \
  disable_output tlv_failure encrypted_alert inner_failure_response

# Lossy protocol handling
use_cache=true

# Where to write logs
output_dir=./logs
