##### hostapd configuration file ##############################################
interface=wlx6470022fd767
# logger_syslog=-1
# logger_syslog_level=2
# logger_stdout=-1
# logger_stdout_level=2

# Interface for separate control program. If this is specified, hostapd
# will create this directory and a UNIX domain socket for listening to requests
# from external programs (CLI/GUI, etc.) for status information and
# configuration. The socket file will be named based on the interface name, so
# multiple hostapd processes/interfaces can be run at the same time if more
# than one interface is used.
# /var/run/hostapd is the recommended directory for sockets and by default,
# hostapd_cli will use it when trying to connect with hostapd.
ctrl_interface=hostapd_ctrl
ctrl_interface_group=0

ssid=eapfuzzer

hw_mode=g
channel=1

auth_algs=1
eapol_version=2

# For both WPA2 and WPA3 we must specify wpa=2
wpa=2

#using internal server
eap_server=1
# CA certificate (PEM or DER file) for EAP-TLS/PEAP/TTLS
ca_cert=certs/ca.pem

# Server certificate (PEM or DER file) for EAP-TLS/PEAP/TTLS
server_cert=certs/server.pem

# Private key matching with the server certificate for EAP-TLS/PEAP/TTLS
# This may point to the same file as server_cert if both certificate and key
# are included in a single file. PKCS#12 (PFX) file (.p12/.pfx) can also be
# used by commenting out server_cert and specifying the PFX file as the
# private_key.
private_key=certs/server.key

# Passphrase for private key
private_key_passwd=whatever

# Use wpa_key_mgmt=SAE for WPA3
wpa_key_mgmt=WPA-EAP
rsn_pairwise=CCMP
#wpa_pairwise=TKIP
wpa_pairwise=CCMP
#wpa_passphrase="password"

#openssl_ciphers=eNULL:@SECLEVEL=0

logger_syslog=-1
logger_syslog_level=4
logger_stdout=-1
logger_stdout_level=4


ieee8021x=1
eap_user_file=hostapd.eap_user

# Optionally you can enable management frame protection
# ieee80211w=1
